---
# this will be useful later to understand if we're on vanilla k8s or OpenShift (OKD)
- name: "Get information about the cluster"
  set_fact:
    api_groups: "{{ lookup('k8s', cluster_info='api_groups') }}"

- name: "Set Smart Gateway container images"
  set_fact:
    events_container_image_path: "{{ lookup('env', 'SMARTGATEWAY_IMAGE') | default('quay.io/infrawatch/smart-gateway:latest', true) }}"
    metrics_container_image_path: "{{ lookup('env', 'METRICS_SMARTGATEWAY_IMAGE') | default('quay.io/infrawatch/sg-core:latest', true) }}"
    bridge_container_image_path: "{{ lookup('env', 'BRIDGE_SMARTGATEWAY_IMAGE') | default('quay.io/infrawatch/sg-bridge:latest', true) }}"

- name: Setup Smart Gateway
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  when: item.to_load | default(True)
  loop:
    - name: events-configmap.yaml.j2
      to_load: "{{ True if 'events' in service_type else False }}"
    - name: deployment.yaml.j2
    - name: service.yaml.j2
      to_load: "{{ True if 'metrics' in service_type else False }}"
