---
- name: Write out configmap for smart gateway
  template:
    dest: /tmp/configmap.yaml
    src: "{{ service_type }}-configmap.yaml.j2"

- name: Smart gateway ConfigMap
  k8s:
    src: /tmp/configmap.yaml

- name: Create deployment for the Smart Gateway
  include_tasks: deployment.yml

- name: Create service for the Smart Gateway
  include_tasks: service.yml
  when: service_type == "metrics"

- name: Create ServiceMonitor for Smart Gateway
  include_tasks: servicemonitor.yml
  when: service_type == "metrics"
