scorecard:
  # Setting a global scorecard option
  output: text
  plugins:
    - basic:
        cr-manifest:
          - "deploy/crds/smartgateway.infra.watch_v2alpha1_smartgateway.metrics_cr.yaml"
    - olm:
        cr-manifest:
          - "deploy/crds/smartgateway.infra.watch_v2alpha1_smartgateway.metrics_cr.yaml"
        csv-path: "deploy/olm-catalog/smart-gateway-operator/1.0.0-beta1/smart-gateway-operator.v1.0.0-beta1.clusterserviceversion.yaml"
