git:
  depth: 1
dist: xenial
languages: python
services:
  - docker
before_install:
  - pip install --upgrade pip --user
  - pip install molecule docker kubernetes openshift jmespath --user
script:
  - molecule --version
  - ansible --version
  - molecule test -s test-local

