git:
  deoth: 1
sudo: required
dist: xenial
languages: python
services:
  - docker
before_install:
  pip install molecule
  pip install docker
script:
  - molecule test
  #- docker build --tag redhat-service-assurance/smart-gateway-operator:latest .
  #- docker images
