env:
  global:
  - secure: MeO4V6CHY8GjebH1n3sTYtq5AG/ohY4MgKr4pDb0P29DxpAtYaqa+lkVBB3lxXGcsE2yY8bEOmHHzA6CQgYpWGHOGihKJbL40HQdQGAajtCStSQcv+AVA4Dq5uwo714Ddx7wovntJbm+zO+Cyv2zczj6407fTvuyJAjf9MMrCkwC23tLr+iCld+juSQlfOtdExzgIegWEhi3z967i9ce70ux4jl9n3jHXaU/6A/o6gJS/Ng5INf8VJ0ZZKnCUwdHYOshjzQAbC+ym24W4oGQTdyJbVAIbxdJMl65VI/h3xcTeS8PJXw9PK9lTS7r7RUDdl8giLTk67TgpYFE/LhuYiq+zAH/5iZSD/Mr0tyblHlpqB9gzDUs2G00IYv7l/RD+BFwReZAXxR9xO2Rsxumtsf+mKm2iu6BkbuzNTudyR2vn4dMGp1lwWwY44ll22nMaek2fjNhgQwB6Ps0xU19NrwpiS7AdyYnYGi9Cg8n59XT5ydwL83jITDk43tZd0IZjX6TcssshqQBzCeXovyzD3O4PsfkBkPer5xoRJ0e/qLLFkQxrv4YNtqxtNzzX9Z3dpYhV0s1sw+ydLTz4/HIMu9tFLkV8F4Zf8r5Yd8NSSKV1E+o8QIXRPATxpJ2OlwG2PiCl7BgYihx8TWXtjnSLDPVJHofw/XAS391DikixRk=
  - secure: IZqzqdEL37CHF3NWEx3jNegfrl9092wpWWezEY4oEVNY1ncUUbZdmzq97gTLtOZ/5lkvm9yMOXZzM20NAl898U8jXp8oj1rX+JowXrXNG7celNIiwag+R9uELOwhSwPkLBF/swmdWf4gErTmFpxIJCERGV9aIuodXd5Wie7U45qn6OExVVp6U4S0VeucOH/SIDDk7V5k4Aaw4MTfNy9Dq6SgMkIxhMhro3Ghxz0NqrZf9BXnrWMxqVIhene7fYrmOvbi1vRrEhgoIROn8mNHD/92sIBEGTQ774lOsX7IMAzXZBH6XeuSLhnH6EZRq0us/evc9c1h8NAIbo4id8x3D4olGWge04PbBoR5hegQLJR4r8Wi0oqGEmiVHb5Uunr1OAjgD9n/ZekeYiUIrt1CLhhNjlTOr4+JW0Ny6X26HuouOG+cIRfKIDtFQjisMLUHgRSFBEqMHrd1ROzekBCFk7MnfSMUq55z176BTnQgGqp+2PFZHI8/Lbh2LhkBfQ477BHieT27nZUbMV3KMyQzrR8SJFTa1p19hqf4Dx9PE1CRe5OzrpzOtYiKwk0RRNKHvrkooPzaojMft0Gj1snweAC4Gipzqs//aTNRZA2jR7RIGsmZsGW+RxDesFyckgCqB0p2kBup/9AnPvS6hLSQQA4BqE4T51UHELi0/Ar/pHA=
os: linux
language: python
git:
  depth: 1
install:
- pip install operator-courier
- pip install ansible-lint
script:
- operator-courier verify --ui_validate_io deploy/olm-catalog/smart-gateway-operator
- ansible-lint roles/smartgateway/
after_success:
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH;
  else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
- "./build/travis/after_success.sh"
