git:
  depth: 1
dist: xenial
languages: python
services:
  - docker
before_install:
  - pip install --upgrade pip
  - pip install molecule docker --user
script:
  - molecule --version
  - ansible --version
  - molecule test
  #- docker build --tag redhat-service-assurance/smart-gateway-operator:latest .
  #- docker images
