FROM scratch

COPY ./manifests /manifests/
COPY ./metadata /metadata/

LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=smart-gateway-operator
LABEL operators.operatorframework.io.bundle.channels.v1=<<BUNDLE_CHANNELS>>
LABEL operators.operatorframework.io.bundle.channel.default.v1=<<BUNDLE_DEFAULT_CHANNEL>>
LABEL operators.operatorframework.io.metrics.mediatype.v1=metrics+v1
LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v0.19.4
LABEL operators.operatorframework.io.metrics.project_layout=ansible
LABEL com.redhat.delivery.operator.bundle=true
LABEL com.redhat.openshift.versions="v4.10-v4.12"
LABEL com.redhat.delivery.backport=false

LABEL com.redhat.component="smart-gateway-operator-bundle-container" \
      name="stf/smart-gateway-operator-bundle" \
      version="<<OPERATOR_BUNDLE_VERSION>>" \
      summary="smart-gateway-operator-bundle" \
      License="ASL 2.0" \
      io.openshift.expose-services="" \
      io.openshift.tags="monitoring,telemetry,faulting,serviceassurance" \
      io.k8s.display-name="smart-gateway-operator-bundle" \
      maintainer="['leif+smart-gateway-operator@redhat.com']" \
      description="smart-gateway-operator-bundle"
