# permissions for end users to view smartgateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smartgateway-viewer-role
rules:
- apiGroups:
  - smartgateway.infra.watch
  resources:
  - smartgateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - smartgateway.infra.watch
  resources:
  - smartgateways/status
  verbs:
  - get
