# permissions for end users to edit smartgateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smartgateway-editor-role
rules:
- apiGroups:
  - smartgateway.infra.watch
  resources:
  - smartgateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - smartgateway.infra.watch
  resources:
  - smartgateways/status
  verbs:
  - get
