apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: smartgateways.smartgateway.infra.watch
spec:
  group: smartgateway.infra.watch
  names:
    kind: SmartGateway
    listKind: SmartGatewayList
    plural: smartgateways
    singular: smartgateway
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
