apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: smartgateways.smartgateway.infra.watch
spec:
  group: smartgateway.infra.watch
  names:
    kind: SmartGateway
    listKind: SmartGatewayList
    plural: smartgateways
    singular: smartgateway
  scope: Namespaced
  version: v2alpha1
  subresources:
    status: {}
  versions:
  - name: v2alpha1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        spec:
          description: 'SmartGatewaySpec is a specification of the desired behavior
            of the Smartgateway deployment. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status'
          properties:
            size:
              description: Size sets the number of replicas to create. Defaults to 1.
              type: integer
            amqp_url:
              description: AMQP1.x listener example 127.0.0.1:5672/collectd/telemetry. Defaults to using
                'messaging-internal-<name>.<namespace>.src:5672/collectd/telemetry'.
              type: string
            use_basic_auth:
              description: Whether to use basic authentication or not when connecting to ElasticSearch. Default is 'false'
              type: boolean
            elastic_url:
              description: URL for ElasticSearch endpoing to connect when the Smart Gateway is operating as an 'events' service type.
                Defaults to 'elasticsearch-es-http.<namespace>.svc:9200'.
              type: string
            elastic_user:
              description: Basic Authentication username for ElasticSearch.
              type: string
            elastic_pass:
              description: Basic Authentication password for ElasticSearch.
              type: string
            tls_secret_name:
              description: Name of the Secret object that holds the TLS certificates and key for Elasticsearch.
                Defaults to 'elasticsearch-es-cert'.
            reset_index:
              description: Reset the ElasticSearch index on load. Defaults to 'false'.
            service_type:
              description: The service type for this smart gateway. One of 'metrics' or 'events'. Defaults to 'metrics'.
              type: string
            exporter_host:
              description: Metrics URL for Prometheus to export. Defaults to "0.0.0.0".
              type: string
            exporter_port:
              description: Metrics port for Prometheus to export. Defaults to 8081.
              type: integer
            cpu_stats:
              description: Include CPU usage info in http requests (degrades performance). Defaults to 'false'.
              type: string
            data_count:
              description: Stop after receiving this many messages in total (-1 forever). Defaults to '-1'.
              type: string
            debug:
              description: Enable verbose debugging statements. Defaults to 'false'.
              type: string
            prefetch:
              description: Number of messages that we can prefetch from AMQP 1.x. By enabling prefetching, the smart gateway won't need to
                request every message individually from the AMQP bus, resulting in a round trip for every request between sender and receiver.
                To avoid the round trip for every message, the use of prefetch can be used to allow the receiver to request messages be sent
                in anticipation of them being sent to us.
              type: integer
            container_image_path:
              description: Path to the container image this Operator will deploy. Value is defined as the standard registry/image_name:tag
                format. Defaults to 'quay.io/infrawatch/smart-gateway:latest'
              type: string
            use_timestamp:
              description: Use the source timestamp (time when data was collected) rather than let Prometheus write when the data was 
                scraped for that metric.
              type: boolean
        status:
          description: Status results of an instance of Smart Gateway
          properties:
            conditions:
              description: The resulting conditions when a Smart Gateway is instantiated
              items:
                properties:
                  status:
                    type: string
                  type:
                    type: string
                  reason:
                    type: string
                  lastTransitionTime:
                    type: string
                type: object
              type: array
          type: object
