apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-gateway-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-gateway-operator
  template:
    metadata:
      labels:
        app: smart-gateway-operator
    spec:
      containers:
      - command:
        - /usr/local/bin/ao-logs
        - /tmp/ansible-operator/runner
        - stdout
        image: quay.io/infrawatch/smart-gateway-operator:v2.0.1
        imagePullPolicy: Always
        name: ansible
        resources: {}
        volumeMounts:
        - mountPath: /tmp/ansible-operator/runner
          name: runner
          readOnly: true
      - env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['olm.targetNamespaces']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: smart-gateway-operator
        - name: ANSIBLE_GATHERING
          value: explicit
        - name: SMARTGATEWAY_IMAGE
          value: quay.io/infrawatch/smart-gateway:v2.0.0
        - name: CORE_SMARTGATEWAY_IMAGE
          value: quay.io/infrawatch/sg-core:v3.0.0
        - name: BRIDGE_SMARTGATEWAY_IMAGE
          value: quay.io/infrawatch/sg-bridge:v1.0.0
        image: quay.io/infrawatch/smart-gateway-operator:v2.0.1
        imagePullPolicy: Always
        name: operator
        resources: {}
        volumeMounts:
        - mountPath: /tmp/ansible-operator/runner
          name: runner
      serviceAccountName: smart-gateway-operator
      volumes:
      - emptyDir: {}
        name: runner
      serviceAccountName: smart-gateway-operator
