apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-gateway-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-gateway-operator
  template:
    metadata:
      labels:
        app: smart-gateway-operator
    spec:
      serviceAccountName: smart-gateway-operator
      containers:
      - name: operator
        image: <<OPERATOR_IMAGE_PULLSPEC>>
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /tmp/ansible-operator/runner
          name: runner
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: smart-gateway-operator
        - name: ANSIBLE_GATHERING
          value: explicit
        - name: ANSIBLE_VERBOSITY_SMARTGATEWAY_SMARTGATEWAY_INFRA_WATCH
          value: 4
        - name: ANSIBLE_DEBUG_LOGS
          value: true
        - name: RELATED_IMAGE_CORE_SMARTGATEWAY_IMAGE
          value: <<RELATED_IMAGE_CORE_SMARTGATEWAY_PULLSPEC>>
        - name: RELATED_IMAGE_BRIDGE_SMARTGATEWAY_IMAGE
          value: <<RELATED_IMAGE_BRIDGE_SMARTGATEWAY_PULLSPEC>>
        - name: RELATED_IMAGE_OAUTH_PROXY_IMAGE
          value: <<RELATED_IMAGE_OAUTH_PROXY_PULLSPEC>>
      volumes:
      - emptyDir: {}
        name: runner
