apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-gateway-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-gateway-operator
  template:
    metadata:
      labels:
        app: smart-gateway-operator
    spec:
      serviceAccountName: smart-gateway-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          image: quay.io/infrawatch/smart-gateway-operator:latest
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          image: quay.io/infrawatch/smart-gateway-operator:latest
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "smart-gateway-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
      volumes:
        - name: runner
          emptyDir: {}
