galaxy_info:
  author: Red Hat CloudOps
  description: Smart Gateway Operator
  company: Red Hat, Inc.

  license: Apache

  min_ansible_version: 2.7

  platforms:
  - name: RHEL
    versions:
    - 7
  - name: CentOS
    versions:
    - 7

  galaxy_tags:
    - monitoring
    - telemetry

dependencies: []
