galaxy_info:
  author: Red Hat CloudOps
  description: Smart Gateway Operator
  company: Red Hat, Inc.

  license: Apache

  min_ansible_version: 2.9

  platforms:
    - name: RHEL
      versions:
        - 8
    - name: CentOS
      versions:
        - 8

  galaxy_tags:
    - monitoring
    - telemetry

dependencies: []
