apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: smartgateways.smartgateway.infra.watch
spec:
  group: smartgateway.infra.watch
  names:
    kind: SmartGateway
    listKind: SmartGatewayList
    plural: smartgateways
    shortNames:
    - sg
    singular: smartgateway
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: 'SmartGatewaySpec is a specification of the desired behavior
            of the Smartgateway deployment. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status'
          properties:
            amqpDataSource:
              description: The expected data source of the messages received from
                the address configured in amqpUrl. Available values include 'universal',
                'collectd', and 'ceilometer'.
              type: string
            amqpUrl:
              description: AMQP1.x listener example 127.0.0.1:5672/collectd/telemetry.
                Defaults to using 'messaging-internal-<name>.<namespace>.src:5672/collectd/telemetry'.
              type: string
            bridgeContainerImagePath:
              description: Path to container image this operator will use for the
                bridge. Value is defined as the standard registry/image_name:tag format
              type: string
            coreContainerImagePath:
              description: Path to container image this operator will use for the
                sg-core. Value is defined as the standard registry/image_name:tag
                format
              type: string
            dataCount:
              description: Stop after receiving this many messages in total (0 forever).
                Defaults to '0'.
              type: integer
            debug:
              description: Enable verbose debugging statements. Defaults to 'false'.
              type: boolean
            elasticPass:
              description: Basic Authentication password for ElasticSearch.
              type: string
            elasticUrl:
              description: URL for ElasticSearch endpoing to connect when the Smart
                Gateway is operating as an 'events' service type. Defaults to 'elasticsearch-es-http.<namespace>.svc:9200'.
              type: string
            elasticUser:
              description: Basic Authentication username for ElasticSearch.
              type: string
            exporterHost:
              description: Metrics URL for Prometheus to export. Defaults to "0.0.0.0".
              type: string
            exporterPort:
              description: Metrics port for Prometheus to export. Defaults to 8081.
              type: integer
            resetIndex:
              description: Reset the ElasticSearch index on load. Defaults to 'false'.
              type: boolean
            serviceType:
              description: The service type for this smart gateway. One of 'metrics'
                or 'events'. Defaults to 'metrics'.
              enum:
              - metrics
              - events
              type: string
            size:
              description: Size sets the number of replicas to create. Defaults to
                1.
              type: integer
            tlsSecretName:
              description: Name of the Secret object that holds the TLS certificates
                and key for Elasticsearch. Defaults to 'elasticsearch-es-cert'.
              type: string
            useBasicAuth:
              description: Whether to use basic authentication or not when connecting
                to ElasticSearch. Default is 'false'
              type: boolean
            useTimestamp:
              description: Use the source timestamp (time when data was collected)
                rather than let Prometheus write when the data was scraped for that
                metric.
              type: boolean
          type: object
        status:
          description: Status results of an instance of Smart Gateway
          properties:
            conditions:
              description: The resulting conditions when a Smart Gateway is instantiated
              items:
                properties:
                  lastTransitionTime:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                type: object
              type: array
          type: object
      type: object
  version: v2alpha1
  versions:
  - name: v2alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
