name: CI
on: push

jobs:
  molecule:
    name: Molecule testing with KinD
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install local kustomize path
        run: make kustomize-local

      - name: Install base dependencies
        run: python -m pip install ansible kubernetes openshift molecule docker

      - name: Install KinD
        run: sudo curl -Lo /usr/bin/kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64 ; sudo chmod +x /usr/bin/kind

      - name: Install Ansible dependencies from requirements.yml
        run: ansible-galaxy collection install -r requirements.yml

      - name: Run molecule test
        run: KUSTOMIZE_PATH="$(pwd)/bin/kustomize" molecule test -s kind

  ansible-linting:
    name: Basic Ansible Linting
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ansible
        run: python -m pip install ansible

      - name: Install operator_sdk.util dependency for Ansible role linting
        run: ansible-galaxy collection install operator_sdk.util

      - name: Install ansible-lint
        run: pip install ansible-lint

      - name: Lint Ansible roles/smartgateway/ directory
        run: ${HOME}/.local/bin/ansible-lint roles/smartgateway

#  super-linting:
#    name: Super Linting
#    runs-on: ubuntu-20.04
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Install operator_sdk.util dependency for Ansible role linting
#        run: ansible-galaxy collection install operator_sdk.util
#
#      - name: Run Super-Linter
#        uses: github/super-linter@v3
#        env:
#          DEFAULT_BRANCH: master
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-check:
    name: Build check
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify image builds
        run: make docker-build

  bundle-check:
    name: Bundle check
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get operator-sdk image
        run: sudo curl --output /usr/local/bin/operator-sdk -JL "https://github.com/operator-framework/operator-sdk/releases/download/$RELEASE_VERSION/operator-sdk_linux_amd64" && sudo chmod +x /usr/local/bin/operator-sdk
        env:
          RELEASE_VERSION: v1.16.0

      - name: Generate bundle
        run: ./build/generate_bundle.sh

      - name: Check bundle validation
        run: operator-sdk bundle validate --verbose ./bundle/
